### ISSUE TITLE
Test Case: Signup_01 | Test the sign-up page front-end functionality | Step #2

### ISSUE THREAD

**Issue by LTOHR** [ASP-Projects-Team-38/Meal-App#20]
Actual Outcome:
When “Sign up” button is selected, the “Re-type Password” fields is highlighted in red and the below error message is displayed:

⚠ Password must contain a minimum of 8 characters, at least 1 uppercase letter, 1 lowercase letter and 1 number.

Comment:
The error message does not align to the reason the user cannot signup. The displayed error message should be for the first password entry i.e. when the password criteria is not met.
Suggest creating an error message informing client to re-type their password or just highlighting the field without an error message.

**Comment by worthyag** [comment]
I fixed this issue now.
