### ISSUE TITLE
Test Case: Recipe_01 | Test the add recipe front-end functionality | Step #3

### ISSUE THREAD

**Issue by LTOHR** [ASP-Projects-Team-38/Meal-App#24]
Action:
Clicking the “Add” Button after filling in the add recipe form

Actual Outcome:
Getting below error when capturing recipe name “Okra soup” but it works when I capture the "Okra" only

Please match the format requested

Comment:
Please show me where to find the format from the code.

Suggest to show the format to the user.

**Comment by worthyag** [comment]
Fixed this, the regex wasn't allowing spaces, now it allows spaces.
